CREATE TABLE `sis_sistema_origen` (
  `id_sistema_origen_pk` int NOT NULL AUTO_INCREMENT,
  `fingerprint_sistema` varchar(8) DEFAULT NULL,
  `id_fuente_origen` int DEFAULT NULL,
  `id_empresa` int DEFAULT NULL,
  `id_pais` int DEFAULT NULL,
  `desc_sistema_origen` varchar(100) DEFAULT NULL,
  `num_identificacion_externo` int DEFAULT '0',
  `cod_color_fondo_hex` varchar(8) DEFAULT NULL,
  `cod_color_fuente_hex` varchar(8) DEFAULT NULL,
  `img_logo` mediumblob,
  `seed_origen_id_sistema_origen_pk` int DEFAULT NULL,
  `flag_registro_eliminado` int DEFAULT '0',
  `cr_fingerprint` varchar(8) DEFAULT NULL,
  `cr_id_user` int DEFAULT NULL,
  `cr_timestamp` datetime DEFAULT NULL,
) ENGINE=InnoDB AUTO_INCREMENT=1369 DEFAULT CHARSET=utf8mb3;

CREATE TABLE `dw_workflow_matching` (
  `ID_PasoWorkflow_PK` int NOT NULL AUTO_INCREMENT,
  `ID_Cuenta` int DEFAULT NULL,
  `NUM_NumeroPaso` int DEFAULT NULL,
  `ID_MetodoMatching` int DEFAULT NULL,
  `VAL_VentanaDiasAntes` int DEFAULT NULL,
  `VAL_VentanaDiasDespues` int DEFAULT NULL,
  `id_tipo_tolerancia` int DEFAULT '1',
  `VAL_ToleranciaImporte` decimal(10,2) DEFAULT NULL,
  `ID_User` int DEFAULT NULL,
  `FLAG_Habilitado` int DEFAULT '1',
  `id_grupo_conciliaciones` int DEFAULT '0',
  `json_campos_matching` varchar(100) DEFAULT NULL,
  `json_sistema_origen_contable` varchar(100) DEFAULT NULL,
  `json_sistema_origen_entidad` varchar(100) DEFAULT NULL,
  `json_tag_contable` varchar(100) DEFAULT '[]',
  `json_tag_entidad` varchar(100) DEFAULT '[]',
  `descripcion_paso` varchar(100) DEFAULT NULL,
  `cant_max_combinaciones` int DEFAULT '3',
  `id_usuario_creacion` int DEFAULT NULL,
  `timestamp_creacion` datetime DEFAULT NULL,
  `desc_informativa_paso` varchar(1000) DEFAULT NULL,
) ENGINE=InnoDB AUTO_INCREMENT=6986 DEFAULT CHARSET=utf8mb3;

CREATE TABLE `dw_cancelaciones` ( 
  `ID_Cancelacion_PK` int NOT NULL AUTO_INCREMENT,
  `ID_TipoCancelacion` int DEFAULT NULL,
  `id_cliente` int DEFAULT NULL,
  `ID_Cuenta` int DEFAULT NULL,
  `ID_TipoMatching` int DEFAULT NULL,
  `NUM_PasoWorkflow` int DEFAULT NULL,
  `Umbral_Tolerancia` decimal(10,2) DEFAULT '0.00',
  `FLAG_CancelacionConAjuste` int DEFAULT '0',
  `Importe_Ajuste_Debe` decimal(15,2) DEFAULT '0.00',
  `Importe_Ajuste_Haber` decimal(15,2) DEFAULT '0.00',
  `Cod_AAAAMM_Ini` int DEFAULT NULL,
  `Cod_AAAAMM_Fin` int DEFAULT NULL,
  `Lista_AAAAMM` varchar(100) DEFAULT NULL,
  `FLAG_InterPeriodos` int DEFAULT '0',
  `Minima_Fecha_Contable` date DEFAULT NULL,
  `Maxima_Fecha_Contable` date DEFAULT NULL,
  `Minima_Fecha_Banco` date DEFAULT NULL,
  `Maxima_Fecha_Banco` date DEFAULT NULL,
  `TimeStamp_Creacion` datetime(3) DEFAULT NULL,
  `ID_User` int DEFAULT NULL,
  `DESC_Descripcion` varchar(1000) DEFAULT NULL,
  `ID_Registro_Lote_Proceso` bigint DEFAULT NULL,
  `id_grupo_conciliaciones` int DEFAULT NULL,
  `id_paso_datamatching` int DEFAULT NULL,
  `id_tipo_estado_conciliacion` int DEFAULT '1',
  `flag_caso_asociado` int DEFAULT '0',
  `id_caso_expediente` int DEFAULT NULL,
  `cant_partidas_conciliadas` int DEFAULT NULL,
  `flag_conciliacion_masiva` int DEFAULT '0',
) ENGINE=InnoDB AUTO_INCREMENT=6735192 DEFAULT CHARSET=utf8mb3;

CREATE TABLE `dw_links` (
  `ID_Link_PK` bigint NOT NULL AUTO_INCREMENT,
  `ID_Cancelacion` int DEFAULT NULL,
  `id_cliente` int DEFAULT NULL,
  `id_cuenta` int DEFAULT NULL,
  `ID_Mov_Contable` bigint DEFAULT NULL,
  `ID_Mov_Entidad` bigint DEFAULT NULL,
  `COD_AAAAMM` int DEFAULT NULL,
) ENGINE=InnoDB AUTO_INCREMENT=19014632 DEFAULT CHARSET=utf8mb3;

CREATE TABLE `dw_movs_contables` (
  `ID_Fila_PK` int NOT NULL AUTO_INCREMENT,
  `id_cliente` int DEFAULT NULL,
  `ID_Cuenta` int DEFAULT NULL,
  `Fecha_Asiento` date DEFAULT '0000-00-00',
  `Cod_AAAAMM` int DEFAULT NULL,
  `cod_fecha_sys` date DEFAULT NULL,
  `Fecha_Maestra` date DEFAULT '0000-00-00',
  `Concepto` varchar(300) DEFAULT NULL,
  `Documento` varchar(50) DEFAULT NULL,
  `Val_Debe` decimal(15,2) DEFAULT NULL,
  `Val_Haber` decimal(15,2) DEFAULT NULL,
  `Nro_Transaccion_Origen` bigint DEFAULT NULL,
  `Nro_Identificacion_Unico` bigint DEFAULT NULL,
  `ID_Clasificacion` varchar(50) DEFAULT NULL,
  `FLG_Debe_Haber` int DEFAULT '0',
  `Cod_Matching` int DEFAULT '0',
  `NUM_PasoWorkflow` int DEFAULT NULL,
  `ID_Tipo_Movimiento` int DEFAULT NULL,
  `Flag_No_Habilitado_Match_Unitario` int DEFAULT '0',
  `flag_conciliado` bit(1) DEFAULT b'0',
  `ID_Cancelacion` int DEFAULT NULL,
  `TimeStamp_Creacion` datetime(3) DEFAULT NULL,
  `ID_User` int DEFAULT NULL,
  `Flag_Error` int DEFAULT '0',
  `Descr_Error` varchar(100) DEFAULT '',
  `ctrl_disable_warning` bit(1) DEFAULT b'0',
  `BData_Empresa_Num` int DEFAULT NULL,
  `BData_Fecha_Presentacion` date DEFAULT NULL,
  `ID_Template_Formato_Archivo` int DEFAULT NULL,
  `id_sistema_origen` int DEFAULT NULL,
  `cod_sistema_origen_externo` int DEFAULT NULL,
  `Ctrl_Nombre_Archivo_Carga` varchar(200) DEFAULT NULL,
  `flag_caso_asociado` int DEFAULT '0',
  `id_caso_asociado` int DEFAULT NULL,
) ENGINE=InnoDB AUTO_INCREMENT=20410262 DEFAULT CHARSET=utf8mb3;

CREATE TABLE `dw_movs_entidad` (
  `ID_Fila_PK` int NOT NULL AUTO_INCREMENT,
  `id_cliente` int DEFAULT NULL,
  `ID_Cuenta` int DEFAULT NULL,
  `Cod_AAAAMM` int DEFAULT NULL,
  `cod_fecha_sys` date DEFAULT NULL,
  `Fecha` date DEFAULT '0000-00-00',
  `Descripcion` varchar(255) DEFAULT NULL,
  `Concepto_Nivel2` varchar(255) DEFAULT NULL,
  `NRO_Referencia` bigint DEFAULT NULL,
  `BData_Cod_Referencia_Char` varchar(45) DEFAULT NULL,
  `Val_Debito` decimal(15,2) DEFAULT NULL,
  `Val_Credito` decimal(15,2) DEFAULT NULL,
  `ID_Clasificacion` varchar(5) DEFAULT NULL,
  `FLG_Debe_Haber` int DEFAULT '0',
  `ID_TipoMovimiento` int DEFAULT NULL,
  `Cod_Matching` int DEFAULT '0',
  `NUM_PasoWorkflow` int DEFAULT NULL,
  `flag_conciliado` bit(1) DEFAULT b'0',
  `ID_Cancelacion` int DEFAULT NULL,
  `TimeStamp_Creacion` datetime(3) DEFAULT NULL,
  `ID_User` int DEFAULT NULL,
  `Flag_Error` int DEFAULT '0',
  `Descr_Error` varchar(100) DEFAULT NULL,
  `ctrl_disable_warning` bit(1) DEFAULT b'0',
  `BData_Empresa_Num` int DEFAULT NULL,
  `BData_Fecha_Presentacion` date DEFAULT NULL,
  `ID_Template_Formato_Archivo` int DEFAULT NULL,
  `id_sistema_origen` int DEFAULT NULL,
  `cod_sistema_origen_externo` int DEFAULT NULL,
  `flag_caso_asociado` int DEFAULT '0',
  `id_caso_asociado` int DEFAULT NULL,
) ENGINE=InnoDB AUTO_INCREMENT=14813547 DEFAULT CHARSET=utf8mb3;

CREATE TABLE `dw_tipo_movimientos` (
  `ID_TipoMovimiento_PK` int NOT NULL AUTO_INCREMENT,
  `fingerprint_tag` varchar(8) DEFAULT NULL,
  `ID_Cuenta` int DEFAULT NULL,
  `id_clase_tag` int DEFAULT '1' COMMENT 'Indica si el TAG es manual o automatico',
  `ID_FuenteOrigen` int DEFAULT NULL,
  `DESC_TipoMovimiento` varchar(200) DEFAULT NULL,
  `TXT_StringReconocer` varchar(200) DEFAULT NULL,
  `flag_tag_importe_debe` int DEFAULT '0',
  `importes_tag_debe` varchar(300) DEFAULT NULL,
  `flag_tag_importe_haber` int DEFAULT '0',
  `importes_tag_haber` varchar(300) DEFAULT NULL,
  `TXT_LabelTipoMov` varchar(20) DEFAULT NULL,
  `FLAG_Default` int DEFAULT '0',
  `FLAG_Registro_Eliminado` int DEFAULT '0',
  `cod_color_hex` varchar(8) DEFAULT NULL,
  `cod_color_hex_fuente_texto` varchar(8) DEFAULT '#ffffff',
  `num_orden_procesamiento` int DEFAULT '0',
  `num_identificacion_externo` int DEFAULT '0',
  `flag_aviso_error_orden` int DEFAULT '0',
  `id_usuario_creacion` int DEFAULT NULL,
  `timestamp_creacion` datetime DEFAULT NULL,
) ENGINE=InnoDB AUTO_INCREMENT=9632 DEFAULT CHARSET=utf8mb3;

CREATE TABLE `sis_template_formato_archivo` (
  `ID_Template_Formato_Archivo_PK` int NOT NULL AUTO_INCREMENT,
  `id_cliente` int DEFAULT NULL,
  `Descripcion_Formato` varchar(45) DEFAULT NULL,
  `ID_Empresa` int DEFAULT NULL,
  `id_pais` int DEFAULT NULL,
  `ID_Fuente_Origen` int DEFAULT NULL,
  `ID_Sistema_Origen` int DEFAULT NULL,
  `ID_Entidad` int DEFAULT NULL,
  `ID_Sistema_Contable` int DEFAULT NULL,
  `ID_Tipo_Archivo` int DEFAULT NULL,
  `num_fila_comienzo_tabla` int DEFAULT NULL,
  `flag_con_cabezales` int DEFAULT '0',
  `flag_habilitado` int DEFAULT '1',
  `cod_caracter_delimitador_csv` char(1) DEFAULT NULL,
  `char_enclosure_csv` char(1) DEFAULT '"',
  `char_escape_csv` char(1) DEFAULT '\\',
  `json_parametros_lectura` varchar(500) DEFAULT NULL,
  `json_variables_parametros` varchar(500) DEFAULT NULL,
  `desc_informativa_importador` varchar(1000) DEFAULT NULL,
  `seed_origen_id_template_formato_archivo_pk` int DEFAULT NULL,
  `cr_fingerprint` varchar(8) DEFAULT NULL,
  `cr_id_user` int DEFAULT NULL,
  `cr_timestamp` datetime DEFAULT NULL,
  `mig_json_refs` varchar(400) DEFAULT NULL,
  `mig_id_process` int DEFAULT NULL,
) ENGINE=InnoDB AUTO_INCREMENT=992 DEFAULT CHARSET=utf8mb3;